Vagrant.configure("2") do |config|
  # Global settings
  config.vm.box = "bento/debian-13"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "2"
  end

  # Server VM
  config.vm.define "jahuangS" do |jahuangS|
    jahuangS.vm.hostname = "jahuangS"
    jahuangS.vm.network "private_network", ip: "192.168.56.110"
	jahuangS.vm.provision "k3s_server", type: "shell", path: "scripts/k3s_server.sh"
  end

  # Server Worker VM
  config.vm.define "jahuangSW" do |jahuangSW|
    jahuangSW.vm.hostname = "jahuangSW"
    jahuangSW.vm.network "private_network", ip: "192.168.56.111"
	jahuangSW.vm.provision "k3s_worker", type: "shell", path: "scripts/k3s_worker.sh"
  end
  
end
